// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Componentebotao from './componentebotao';
import './adicionarprojeto.css';


function render() {
    return <div className="adicionarprojeto-adicionarprojeto-4">
        <div className="adicionarprojeto-0">
            <div className="adicionarprojeto-text_2">Novo Projeto</div>
        </div>
        <div className="adicionarprojeto-1">
            <div className="adicionarprojeto-1-0">
                <div className="adicionarprojeto-1-0-0">
                    <div className="adicionarprojeto-text_21">
                        {"Nome do Projeto:"}
                    </div>
                </div>
            </div>
            <input type="text" placeholder="Placeholder" value={this.props.nomeProjeto} className="adicionarprojeto-nomeprojeto-3" /> 
        </div>
        <div className="adicionarprojeto-2">
            <div className="adicionarprojeto-2-0">
                <div className="adicionarprojeto-2-0-0">
                    <div className="adicionarprojeto-text_22">
                        {"Descrição:"}
                    </div>
                </div>
            </div>
            <textarea placeholder="Placeholder" value={this.props.descricao} className="adicionarprojeto-descricao-3" /> 
        </div>
        <div className="adicionarprojeto-3">
            <div className="adicionarprojeto-3-0">
                <div className="adicionarprojeto-3-0-0">
                    <div className="adicionarprojeto-text_23">
                        {"Equipes:"}
                    </div>
                </div>
            </div>
            <input type="text" placeholder="Placeholder" value={this.props.idEquipes} className="adicionarprojeto-idequipes-2" /> 
        </div>
        <div className="adicionarprojeto-4">
            <div className="adicionarprojeto-4-0">
                <div className="adicionarprojeto-4-0-0">
                    <div className="adicionarprojeto-text_24">{"Prazo:"}</div>
                </div>
            </div>
            <div className="adicionarprojeto-4-1">
                <div className="adicionarprojeto-4-1-0">
                    <input type="text" placeholder="Placeholder" value={this.props.prazo} className="adicionarprojeto-prazo-4" /> 
                </div>
            </div>
            <div className="adicionarprojeto-botaosalvar-4">
                <Componentebotao textoBotao={"Salvar"} /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
