// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Componentebotao from './componentebotao';
import './adicionarprojeto.css';


function render() {
    return <div className="adicionarprojeto-adicionarprojeto-4">
        <div className="adicionarprojeto-0">
            <div className="adicionarprojeto-text_2">Novo Projeto</div>
        </div>
        <div className="adicionarprojeto-1">
            <div className="adicionarprojeto-1-0">
                <div className="adicionarprojeto-1-0-0">
                    <div className="adicionarprojeto-text_21">
                        {"Nome do Projeto:"}
                    </div>
                </div>
            </div>
            <input type="text" placeholder="Meu Projeto" value={this.props.nomeProjeto} onChange={(e) => this.props.setNomeProjeto(e.target.value)} className="adicionarprojeto-nomeprojeto-3" /> 
        </div>
        <div className="adicionarprojeto-2">
            <div className="adicionarprojeto-2-0">
                <div className="adicionarprojeto-2-0-0">
                    <div className="adicionarprojeto-text_22">
                        {"Descrição:"}
                    </div>
                </div>
            </div>
            <textarea placeholder="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia dui leo, lobortis pulvinar est hendrerit at." value={this.props.descricao} onChange={(e) => this.props.setDescricao(e.target.value)} className="adicionarprojeto-descricao-3" /> 
        </div>
        <div className="adicionarprojeto-3">
            <div className="adicionarprojeto-3-0">
                <div className="adicionarprojeto-3-0-0">
                    <div className="adicionarprojeto-text_23">
                        {"Equipes:"}
                    </div>
                </div>
            </div>
            <input type="text" placeholder="23, 47, 10" value={this.props.idEquipes} onChange={(e) => this.props.setIdEquipes(e.target.value)} className="adicionarprojeto-idequipes-2" /> 
        </div>
        <div className="adicionarprojeto-4">
            <div className="adicionarprojeto-4-0">
                <div className="adicionarprojeto-4-0-0">
                    <div className="adicionarprojeto-4-0-0-0">
                        <div className="adicionarprojeto-4-0-0-0-0">
                            <div className="adicionarprojeto-text_24">{"Prazo:"}</div>
                        </div>
                    </div>
                    <input type="text" placeholder="aaaa-mm-dd" value={this.props.prazo} onChange={(e) => this.props.setPrazo(e.target.value)} className="adicionarprojeto-prazo-4" /> 
                </div>
                <div className="adicionarprojeto-4-0-1">
                    <div className="adicionarprojeto-mensagemerro-8">
                        { this.props.mensagemErro }
                    </div>
                </div>
            </div>
            <div className="adicionarprojeto-4-1">
                <div className="adicionarprojeto-4-1-0">
                    <div className="adicionarprojeto-rectangle_1">
                        <div className="adicionarprojeto-4-1-0-0-0">
                            <div onClick={this.props.handleClick} className="adicionarprojeto-botaosalvar-4">
                                <Componentebotao textoBotao={"Salvar"} color={this.props.corBotao} /> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
