// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Componentebotao from './componentebotao';
import './adicionartarefa.css';


function render() {
    return <div className="adicionartarefa-adicionartarefa-0">
        <div className="adicionartarefa-0">
            <div className="adicionartarefa-text_2">Nova Tarefa</div>
        </div>
        <div className="adicionartarefa-1">
            <div className="adicionartarefa-1-0">
                <div className="adicionartarefa-1-0-0">
                    <div className="adicionartarefa-text_27">
                        {"Nome da Tarefa:"}
                    </div>
                </div>
            </div>
            <input type="text" placeholder="Nome" value={this.props.nomeTarefa} onChange={(e) => this.props.setNomeTarefa(e.target.value)} className="adicionartarefa-nometarefa-1" /> 
        </div>
        <div className="adicionartarefa-2">
            <div className="adicionartarefa-2-0">
                <div className="adicionartarefa-2-0-0">
                    <div className="adicionartarefa-text_28">{"Tags:"}</div>
                </div>
            </div>
            <input type="text" placeholder="uma, outra" value={this.props.tags} onChange={(e) => this.props.setTags(e.target.value)} className="adicionartarefa-tags-7" /> 
        </div>
        <div className="adicionartarefa-3">
            <div className="adicionartarefa-3-0">
                <div className="adicionartarefa-3-0-0">
                    <div className="adicionartarefa-text_29">
                        {"Descrição:"}
                    </div>
                </div>
            </div>
            <textarea placeholder="texto" value={this.props.descricao} onChange={(e) => this.props.setDescricao(e.target.value)} className="adicionartarefa-descricao-8" /> 
        </div>
        <div className="adicionartarefa-4">
            <div className="adicionartarefa-4-0">
                <div className="adicionartarefa-4-0-0">
                    <div className="adicionartarefa-text_3">
                        {"Responsáveis:"}
                    </div>
                </div>
            </div>
            <input type="text" placeholder="usuario1, usuario2" value={this.props.responsaveis} onChange={(e) => this.props.setResponsaveis(e.target.value)} className="adicionartarefa-responsaveis-4" /> 
        </div>
        <div className="adicionartarefa-5">
            <div className="adicionartarefa-5-0">
                <div className="adicionartarefa-5-0-0">
                    <div className="adicionartarefa-text_31">{"Prazo:"}</div>
                </div>
            </div>
            <input type="text" placeholder="aaaa-mm-dd" value={this.props.data} onChange={(e) => this.props.setPrazo(e.target.value)} className="adicionartarefa-data-6" /> 
        </div>
        <div className="adicionartarefa-6">
            <div className="adicionartarefa-6-0">
                <div className="adicionartarefa-6-0-0">
                    <div className="adicionartarefa-text_30">
                        {"Dependências:"}
                    </div>
                </div>
            </div>
            <input type="text" placeholder="32, 47, 58" value={this.props.dependencias} onChange={(e) => this.props.setDependencias(e.target.value)} className="adicionartarefa-responsaveis-8" /> 
        </div>
        <div className="adicionartarefa-7">
            <div className="adicionartarefa-7-0">
                <div className="adicionartarefa-7-0-0">
                    <div className="adicionartarefa-mensagemerro-5">
                        { this.props.mensagemErro }
                    </div>
                </div>
            </div>
            <div onClick={this.props.handleClick} className="adicionartarefa-rectangle_1">
                <div className="adicionartarefa-7-1-0">
                    <div className="adicionartarefa-botaosalvar-4">
                        <Componentebotao textoBotao={"Salvar"} color={this.props.corBotao} /> 
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
