// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Componentebotao from './componentebotao';
import './adicionarrepositorio.css';


function render() {
    return <div className="adicionarrepositorio-adicionarrepositorio-1">
        <div className="adicionarrepositorio-0">
            <div className="adicionarrepositorio-titulo-5">
                {"Adicionar Repositório Existente"}
            </div>
        </div>
        <div className="adicionarrepositorio-1">
            <div className="adicionarrepositorio-1-0">
                <div className="adicionarrepositorio-1-0-0">
                    <div className="adicionarrepositorio-nome-9">
                        {"Nome:"}
                    </div>
                </div>
            </div>
            <input type="text" value={this.props.nome} className="adicionarrepositorio-nome-7" /> 
        </div>
        <div className="adicionarrepositorio-2">
            <div className="adicionarrepositorio-2-0">
                <div className="adicionarrepositorio-2-0-0">
                    <div className="adicionarrepositorio-link-5">
                        {"Link:"}
                    </div>
                </div>
            </div>
            <input type="text" value={this.props.link} className="adicionarrepositorio-link-4" /> 
        </div>
        <div className="adicionarrepositorio-3">
            <div className="adicionarrepositorio-componentebotao_instance-3">
                <Componentebotao textoBotao={"Adicionar"} /> 
            </div>
        </div>
        <div className="adicionarrepositorio-4">
            <div className="adicionarrepositorio-textogithub-5">
                {"Não criou ainda?"}
            </div>
        </div>
        <div className="adicionarrepositorio-5">
            <div className="adicionarrepositorio-github-7">
                {"Como criar repositório Github"}
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
