// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import './arquivo.css';


function render() {
    return <div className="arquivo-arquivo-9">
        <div className="arquivo-0">
            <div onClick={this.props.handleClick} className="arquivo-rectangle_2">
                <div className="arquivo-0-0-0">
                    <img src={this.props.icone} className="arquivo-icone-8" /> 
                </div>
                <div className="arquivo-0-0-1">
                    <div className="arquivo-nome-1">{ this.props.nome }</div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
