// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import './barratarefas.css';


function render() {
    return <div className="barratarefas-barratarefas-4">
        <div className="barratarefas-0">
            <div className="barratarefas-barratarefa-5" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
