// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import './botao_menu.css';


function render() {
    return <div className="pd-onactive-parent pd-onhover-parent botao_menu">
        <div className="pd-onactive botao_menu-_active-2">
            <div className="botao_menu-0-0">
                <div className="botao_menu-text-0">
                    { this.props.item }
                </div>
                <div className="botao_menu-0-0-1" /> 
            </div>
        </div>
        <div className="pd-onhover botao_menu-_hover-5">
            <div className="botao_menu-1-0" /> 
            <div className="botao_menu-1-1">
                <div className="botao_menu-text-9">
                    { this.props.item }
                </div>
                <div className="botao_menu-1-1-1" /> 
            </div>
            <div className="botao_menu-1-2" /> 
            <div className="botao_menu-1-3">
                <div className="botao_menu-rectangle-8" /> 
                <div className="botao_menu-1-3-1" /> 
            </div>
        </div>
        { (('default') === "default") ?
            <div className="botao_menu-default-7">
                <div className="botao_menu-2-0-0">
                    <div className="botao_menu-text-2">
                        { this.props.item }
                    </div>
                    <div className="botao_menu-2-0-0-1" /> 
                </div>
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
