// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Componentebotao from './componentebotao';
import Tarefareduzida from './tarefareduzida';
import './centrotarefas.css';


function render() {
    return <div className="centrotarefas-centrotarefas-7">
        <div className="centrotarefas-0">
            <div className="centrotarefas-0-0">
                <div className="centrotarefas-0-0-0">
                    <div className="centrotarefas-text_2">
                        { this.props.nomeProjeto }
                    </div>
                </div>
            </div>
            <a href="/tarefas/nova" className="centrotarefas-0-1">
                <div className="centrotarefas-botaoadicionarprojeto-3">
                    <Componentebotao textoBotao={"Adicionar Tarefa"} /> 
                </div>
            </a>
        </div>
        <div className="centrotarefas-1">
            <div className="centrotarefas-1-0">
                { this.props.listaTarefas.map((elem, i) => {
                    return <div key={i} className="centrotarefas-rectangle_1">
                        <div className="centrotarefas-1-0-0-0-0">
                            <div className="centrotarefas-tarefareduzida_instance-4">
                                <Tarefareduzida nomeTarefa={elem.nomeTarefa} progresso={elem.corProgresso} prazo={elem.prazo} responsaveis={elem.responsaveis} /> 
                            </div>
                        </div>
                        <div className="centrotarefas-1-0-0-0-1">
                            <div className="centrotarefas-line_5" /> 
                        </div>
                    </div>;
                }) }
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
