// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Componentebotao from './componentebotao';
import './centordetalheequipe.css';


function render() {
    return <div className="centordetalheequipe-centordetalheequipe-1">
        <div className="centordetalheequipe-0">
            <div className="centordetalheequipe-titulo-5">
                { this.props.nomeEquipe }
            </div>
        </div>
        <div className="centordetalheequipe-1">
            <div className="centordetalheequipe-link-9">
                {"Usuários Membros:"}
            </div>
            <div className="centordetalheequipe-1-1">
                <div className="centordetalheequipe-1-1-0">
                    <input type="text" placeholder="Placeholder" value={this.props.membros} onChange={(e) => this.props.setMembros(e.target.value)} className="centordetalheequipe-responsaveis-6" /> 
                </div>
            </div>
        </div>
        <div className="centordetalheequipe-2">
            <div className="centordetalheequipe-rectangle_1">
                <div className="centordetalheequipe-2-0-0">
                    <div onClick={this.props.handleClick} className="centordetalheequipe-componentebotao_instance-0">
                        <Componentebotao textoBotao={"Salvar"} /> 
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
