// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import './componentebotao.css';


function render() {
    return <div className="componentebotao-componentebotao-2">
        <div className="componentebotao-0">
            <div className="componentebotao-0-0" /> 
            <div className="componentebotao-botaoadicionararquivo-2">
                <div className="componentebotao-0-1-0">
                    <div className="componentebotao-text_1">
                        { this.props.textoBotao }
                    </div>
                </div>
            </div>
            <div className="componentebotao-0-2" /> 
        </div>
        <div className="componentebotao-1" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
