// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import './componentearquivo.css';


function render() {
    return <div className="componentearquivo-componentearquivo-1">
        <div className="componentearquivo-0">
            <img src={this.props.img_src} className="componentearquivo-image_2" /> 
        </div>
        <div className="componentearquivo-1">
            <div className="componentearquivo-text_1">
                { this.props.text }
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
