// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Componentebotao from './componentebotao';
import './detalhesprojeto.css';


function render() {
    return <div className="detalhesprojeto-detalhesprojeto-9">
        <div className="detalhesprojeto-0">
            <div className="detalhesprojeto-text_2">Projeto X</div>
        </div>
        <div className="detalhesprojeto-1">
            <div className="detalhesprojeto-text_22">
                {"Descrição:"}
            </div>
            <div className="detalhesprojeto-type_something-7">
                Type something
            </div>
        </div>
        <div className="detalhesprojeto-2">
            <div className="detalhesprojeto-2-0">
                <div className="detalhesprojeto-2-0-0">
                    <div className="detalhesprojeto-text_23">{"Equipes:"}</div>
                </div>
            </div>
            <input type="text" placeholder="Placeholder" value={this.props.idEquipes} className="detalhesprojeto-idequipes-7" /> 
        </div>
        <div className="detalhesprojeto-3">
            <div className="detalhesprojeto-3-0">
                <div className="detalhesprojeto-3-0-0">
                    <div className="detalhesprojeto-text_24">{"Prazo:"}</div>
                </div>
            </div>
            <input type="text" placeholder="Placeholder" value={this.props.prazo} className="detalhesprojeto-prazo-6" /> 
        </div>
        <div className="detalhesprojeto-4">
            <div className="detalhesprojeto-botaosalvar-2">
                <Componentebotao textoBotao={"Salvar"} /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
