// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Componentebotao from './componentebotao';
import './detalhesprojeto.css';


function render() {
    return <div className="detalhesprojeto-detalhesprojeto-9">
        <div className="detalhesprojeto-0">
            <div className="detalhesprojeto-text_2">
                { this.props.nomeProjeto }
            </div>
        </div>
        <div className="detalhesprojeto-1">
            <div className="detalhesprojeto-1-0">
                <div className="detalhesprojeto-1-0-0">
                    <div className="detalhesprojeto-text_22">
                        {"Descrição:"}
                    </div>
                </div>
            </div>
            <textarea placeholder="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia dui leo, lobortis pulvinar est hendrerit at." value={this.props.descricao} onChange={(e) => this.props.setDescricao(e.target.value)} className="detalhesprojeto-descricao-7" /> 
        </div>
        <div className="detalhesprojeto-2">
            <div className="detalhesprojeto-2-0">
                <div className="detalhesprojeto-2-0-0">
                    <div className="detalhesprojeto-text_23">{"Equipes:"}</div>
                </div>
            </div>
            <input type="text" placeholder="1, 32, 41" value={this.props.idEquipes} onChange={(e) => this.props.setIdEquipes(e.target.value)} className="detalhesprojeto-idequipes-7" /> 
        </div>
        <div className="detalhesprojeto-3">
            <div className="detalhesprojeto-3-0">
                <div className="detalhesprojeto-3-0-0">
                    <div className="detalhesprojeto-text_24">{"Prazo:"}</div>
                </div>
            </div>
            <input type="text" placeholder="aaaa-mm-dd" value={this.props.prazo} onChange={(e) => this.props.setPrazo(e.target.value)} className="detalhesprojeto-prazo-6" /> 
        </div>
        <div className="detalhesprojeto-4">
            <div className="detalhesprojeto-rectangle_2">
                <div className="detalhesprojeto-4-0-0">
                    <div onClick={this.props.handleClick} className="detalhesprojeto-botaosalvar-2">
                        <Componentebotao textoBotao={"Salvar"} color={"rgb(17, 39, 73)"} /> 
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
