// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import './documento.css';


function render() {
    return <div className="documento-documento-9">
        <div className="documento-0">
            <img src="https://ucarecdn.com/e762750c-d86d-4076-9026-9781a82cf2e0/" className="documento-doc_5" /> 
        </div>
        <div className="documento-1">
            <div className="documento-text_9">documento 1</div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
