// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import './feedback.css';


function render() {
    return <div className="feedback-feedback-8">
        <div className="feedback-0">
            <div className="feedback-line_2" /> 
        </div>
        <div className="feedback-1">
            <div className="feedback-autor-3">
                { this.props.autor }
            </div>
        </div>
        <div className="feedback-2">
            <div className="feedback-textofeedback-8">
                { this.props.textoFeedback }
            </div>
        </div>
        <div className="feedback-3">
            <div className="feedback-ratingfeedback-4">
                { this.props.ratingFeedback }
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
