// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import './iconepessoa.css';


function render() {
    return <div className="pd-onhover-parent iconepessoa">
        { (('default') === "default") ?
            <div className="iconepessoa-default-4">
                <div className="iconepessoa-0-0-0">
                    <div className="iconepessoa-oval_2">
                        <div className="iconepessoa-0-0-0-0-0">
                            <img src="https://ucarecdn.com/7b47cb9a-5afc-41ed-929c-73ad0016edc3/" className="iconepessoa-image_6" /> 
                        </div>
                    </div>
                    <div className="iconepessoa-0-0-0-1">
                        <div className="iconepessoa-0-0-0-1-0">
                            <div className="iconepessoa-text_7">
                                { this.props.nomeUsuario }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        : null}
        <div className="pd-onhover iconepessoa-_hover-4">
            <div className="iconepessoa-1-0">
                <div className="iconepessoa-rectangle_9">
                    <div className="iconepessoa-1-0-0-0">
                        <a href="/projetos" className="iconepessoa-1-0-0-0-0">
                            <div className="iconepessoa-text_1">Projetos</div>
                        </a>
                    </div>
                    <div className="iconepessoa-1-0-0-1">
                        <div className="iconepessoa-line-2" /> 
                    </div>
                    <div className="iconepessoa-1-0-0-2">
                        <a href="/equipes" className="iconepessoa-1-0-0-2-0">
                            <div className="iconepessoa-text_11">Equipes</div>
                        </a>
                    </div>
                    <div className="iconepessoa-1-0-0-3">
                        <div className="iconepessoa-line_4" /> 
                    </div>
                    <div className="iconepessoa-1-0-0-4">
                        <a href="/" className="iconepessoa-1-0-0-4-0">
                            <div className="iconepessoa-text_11-5">Logout</div>
                        </a>
                    </div>
                </div>
                <div className="iconepessoa-1-0-1">
                    <div className="iconepessoa-1-0-1-0">
                        <div className="iconepessoa-triangle-1">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 23" className="iconepessoa-1-0-1-0-0-0">
                                <polygon points="0 0 0 23 16 23" className="iconepessoa-1-0-1-0-0-0-0" /> 
                            </svg>
                        </div>
                    </div>
                    <div className="iconepessoa-1-0-1-1">
                        <div className="iconepessoa-triangle-7">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 23" className="iconepessoa-1-0-1-1-0-0">
                                <polygon points="0 23 16 0 0 0" className="iconepessoa-1-0-1-1-0-0-0" /> 
                            </svg>
                        </div>
                    </div>
                </div>
                <div className="iconepessoa-1-0-2">
                    <div className="iconepessoa-1-0-2-0">
                        <div className="iconepessoa-oval_2-2">
                            <div className="iconepessoa-1-0-2-0-0-0">
                                <img src="https://ucarecdn.com/7b47cb9a-5afc-41ed-929c-73ad0016edc3/" className="iconepessoa-image_6-3" /> 
                            </div>
                        </div>
                    </div>
                </div>
                <div className="iconepessoa-1-0-3">
                    <div className="iconepessoa-1-0-3-0">
                        <div className="iconepessoa-text_7-5">
                            { this.props.nomeUsuario }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
