// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import './iconeprojeto.css';


function render() {
    return <div className="iconeprojeto-iconeprojeto-5">
        <div className="iconeprojeto-0">
            <img src={this.props.imagemProjeto} className="iconeprojeto-imagemprojeto-9" /> 
        </div>
        <div className="iconeprojeto-1">
            <div className="iconeprojeto-nomeprojeto-0">
                { this.props.nomeProjeto }
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
