// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import './materialuitextinput.css';
import TextField from 'material-ui/TextField';


function render() {
    return <div className="materialuitextinput-materialuitextinput-9">
        <TextField  fullWidth={true} {...this.props} />
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
