// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import './pasta.css';


function render() {
    return <div className="pasta-pasta-9">
        <div className="pasta-0">
            <img src="https://ucarecdn.com/c51262cd-dd28-4d7b-919b-e3c7df27c960/" className="pasta-image-8" /> 
        </div>
        <div className="pasta-1">
            <div className="pasta-text_1">Pasta </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
