// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import './semanticuidropdown.css';
import {Dropdown} from 'semantic-ui-react';


function render() {
    return <div className="semanticuidropdown-semanticuidropdown-8">
        <Dropdown fluid selection {...this.props} />
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
