// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import './tarefareduzida.css';


function render() {
    return <div className="tarefareduzida-tarefareduzida-4">
        <div className="tarefareduzida-0">
            <div className="tarefareduzida-0-0">
                <div className="tarefareduzida-0-0-0">
                    <div className="tarefareduzida-titulotarefa-1">
                        { this.props.nomeTarefa }
                    </div>
                </div>
            </div>
            <div className="tarefareduzida-0-1">
                <div className="tarefareduzida-0-1-0">
                    <div className="tarefareduzida-statusprogresso-2" style={{"background": this.props.progresso}} /> 
                </div>
            </div>
        </div>
        <div className="tarefareduzida-1">
            <div className="tarefareduzida-tituloprazo-9">
                {"Prazo:"}
            </div>
            <div className="tarefareduzida-1-1">
                <div className="tarefareduzida-1-1-0">
                    <div className="tarefareduzida-prazo-6">
                        { this.props.prazo }
                    </div>
                </div>
            </div>
        </div>
        <div className="tarefareduzida-2">
            <div className="tarefareduzida-tituloresponsavel-6">
                {"Responsáveis:"}
            </div>
            <div className="tarefareduzida-2-1">
                <div className="tarefareduzida-2-1-0">
                    <div className="tarefareduzida-responsaveis-2">
                        { this.props.responsaveis }
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
