// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import './tarefabarratarefas.css';


function render() {
    return <div className="tarefabarratarefas-tarefabarratarefas-2">
        <div className="tarefabarratarefas-0">
            <div className="tarefabarratarefas-text_3">
                { this.props.resourceTarefa }
            </div>
        </div>
        <div className="tarefabarratarefas-1">
            <div onClick={() => { window.location = this.props.resourceTarefa; }} className="tarefabarratarefas-text_1">
                { this.props.nomeTarefa }
            </div>
        </div>
        <div className="tarefabarratarefas-2">
            <div className="tarefabarratarefas-text_19">
                { this.props.descricao }
            </div>
        </div>
        <div className="tarefabarratarefas-3" /> 
        <div className="tarefabarratarefas-4">
            <div className="tarefabarratarefas-rectangle_1">
                <div className="tarefabarratarefas-4-0-0">
                    <div className="tarefabarratarefas-4-0-0-0">
                        <div className="tarefabarratarefas-4-0-0-0-0">
                            <div className="tarefabarratarefas-tituloprazo-6">
                                {"Prazo:"}
                            </div>
                        </div>
                    </div>
                    <div className="tarefabarratarefas-4-0-0-1">
                        <div className="tarefabarratarefas-4-0-0-1-0">
                            <div className="tarefabarratarefas-12">
                                { this.props.prazo }
                            </div>
                        </div>
                    </div>
                    <div className="tarefabarratarefas-statusprogresso-3" style={{"background": this.props.progresso}} /> 
                </div>
                <div className="tarefabarratarefas-4-0-1">
                    <div className="tarefabarratarefas-line_3" /> 
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
