// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Componentebotao from './componentebotao';
import Feedback from './feedback';
import './tarefadetalhada.css';


function render() {
    return <div className="tarefadetalhada-tarefadetalhada-9">
        <div className="tarefadetalhada-0">
            <div className="tarefadetalhada-0-0">
                <div className="tarefadetalhada-0-0-0">
                    <div className="tarefadetalhada-titulotarefa-2">
                        { this.props.tituloTarefa }
                    </div>
                </div>
            </div>
            <div className="tarefadetalhada-oval-4" style={{"background": this.props.progresso}} /> 
        </div>
        <div className="tarefadetalhada-1">
            <div className="tarefadetalhada-1-0">
                <div className="tarefadetalhada-1-0-0">
                    <div className="tarefadetalhada-text_3">{"Prazo:"}</div>
                </div>
            </div>
            <input type="text" placeholder="Placeholder" value={this.props.prazo} className="tarefadetalhada-prazo-0" /> 
        </div>
        <div className="tarefadetalhada-2">
            <div className="tarefadetalhada-2-0">
                <div className="tarefadetalhada-2-0-0">
                    <div className="tarefadetalhada-text_4">
                        {"Responsáveis:"}
                    </div>
                </div>
            </div>
            <input type="text" placeholder="Placeholder" value={this.props.responsaveis} className="tarefadetalhada-responsaveis-1" /> 
        </div>
        <div className="tarefadetalhada-3">
            <div className="tarefadetalhada-3-0">
                <div className="tarefadetalhada-3-0-0">
                    <div className="tarefadetalhada-text_2">
                        {"Duração Esperada:"}
                    </div>
                </div>
            </div>
            <input type="text" placeholder="Placeholder" value={this.props.duracao} className="tarefadetalhada-duracao-5" /> 
        </div>
        <div className="tarefadetalhada-4">
            <div className="tarefadetalhada-4-0">
                <div className="tarefadetalhada-4-0-0">
                    <div className="tarefadetalhada-text_6">{"Tags:"}</div>
                </div>
            </div>
            <input type="text" placeholder="Placeholder" value={this.props.tags} className="tarefadetalhada-text_input_5" /> 
        </div>
        <div className="tarefadetalhada-5">
            <div className="tarefadetalhada-5-0">
                <div className="tarefadetalhada-5-0-0">
                    <div className="tarefadetalhada-text_8">
                        {"Dependências:"}
                    </div>
                </div>
            </div>
            <input type="text" placeholder="Placeholder" value={this.props.dependencias} className="tarefadetalhada-dependencias-9" /> 
        </div>
        <div className="tarefadetalhada-6">
            <div className="tarefadetalhada-botaosalvar-2">
                <Componentebotao textoBotao={"Salvar"} /> 
            </div>
        </div>
        <div className="tarefadetalhada-7">
            <div className="tarefadetalhada-text_1">Feedbacks</div>
        </div>
        <div className="tarefadetalhada-8">
            <input type="text" placeholder="Escreva aqui seu feedback" value={this.props.feedbackInput} className="tarefadetalhada-feedbackinput-6" /> 
        </div>
        <div className="tarefadetalhada-9">
            <div className="tarefadetalhada-9-0">
                <div className="tarefadetalhada-9-0-0">
                    <input type="text" placeholder="Placeholder" value={this.props.ratingInput} className="tarefadetalhada-ratinginput-4" /> 
                </div>
            </div>
            <div className="tarefadetalhada-botaoenviar-3">
                <Componentebotao textoBotao={"Enviar"} /> 
            </div>
        </div>
        <div className="tarefadetalhada-10">
            <div className="tarefadetalhada-10-0">
                { this.props.listaFeedbacks.map((elem, i) => {
                    return <div key={i} className="tarefadetalhada-rectangle_1">
                        <div className="tarefadetalhada-10-0-0-0-0">
                            <div className="tarefadetalhada-feedback_instance-9">
                                <Feedback autor={elem.autor} textoFeedback={elem.textoFeedback} ratingFeedback={elem.ratingFeedback} /> 
                            </div>
                        </div>
                    </div>;
                }) }
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
