// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import './tarefabarratarefas.css';


function render() {
    return <div className="tarefabarratarefas-tarefabarratarefas-2">
        <div className="tarefabarratarefas-0">
            <div className="tarefabarratarefas-rectangle_1">
                <div className="tarefabarratarefas-0-0-0">
                    <div className="tarefabarratarefas-text_1">
                        Titulo da tarefa
                    </div>
                </div>
                <div className="tarefabarratarefas-0-0-1">
                    <div className="tarefabarratarefas-line_3" /> 
                </div>
                <div className="tarefabarratarefas-0-0-2">
                    <div className="tarefabarratarefas-text_19">
                        {"Descrição tarefa"}
                    </div>
                </div>
                <div className="tarefabarratarefas-0-0-3">
                    <div className="tarefabarratarefas-0-0-3-0">
                        <div className="tarefabarratarefas-0-0-3-0-0">
                            <div className="tarefabarratarefas-tituloprazo-6">
                                {"Prazo:"}
                            </div>
                        </div>
                    </div>
                    <div className="tarefabarratarefas-0-0-3-1">
                        <div className="tarefabarratarefas-0-0-3-1-0">
                            <input type="text" placeholder="Placeholder" value={this.props.prazo} className="tarefabarratarefas-prazo-0" /> 
                        </div>
                    </div>
                    <div className="tarefabarratarefas-statusprogresso-3" style={{"background": this.props.color}} /> 
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
