// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Componentebotao from './componentebotao';
import Feedback from './feedback';
import './tarefadetalhada.css';


function render() {
    return <div className="tarefadetalhada-tarefadetalhada-9">
        <div className="tarefadetalhada-0">
            <div className="tarefadetalhada-0-0">
                <div className="tarefadetalhada-0-0-0">
                    <div className="tarefadetalhada-titulotarefa-2">
                        { this.props.nomeTarefa }
                    </div>
                </div>
            </div>
            <div className="tarefadetalhada-oval-4" style={{"background": this.props.progresso}} /> 
        </div>
        <div className="tarefadetalhada-1">
            <div className="tarefadetalhada-1-0">
                <div className="tarefadetalhada-1-0-0">
                    <div className="tarefadetalhada-text_3">{"Prazo:"}</div>
                </div>
            </div>
            <input type="text" placeholder="aaaa-mm-dd" value={this.props.prazo} onChange={(e) => this.props.setPrazo(e.target.value)} className="tarefadetalhada-prazo-0" /> 
        </div>
        <div className="tarefadetalhada-2">
            <div className="tarefadetalhada-2-0">
                <div className="tarefadetalhada-2-0-0">
                    <div className="tarefadetalhada-text_4">
                        {"Responsáveis:"}
                    </div>
                </div>
            </div>
            <input type="text" placeholder="usuario1, usuario2" value={this.props.responsaveis} onChange={(e) => this.props.setResponsaveis(e.target.value)} className="tarefadetalhada-responsaveis-1" /> 
        </div>
        <div className="tarefadetalhada-3">
            <div className="tarefadetalhada-3-0">
                <div className="tarefadetalhada-3-0-0">
                    <div className="tarefadetalhada-text_2">
                        {"Descrição:"}
                    </div>
                </div>
            </div>
            <textarea placeholder="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia dui leo, lobortis pulvinar est hendrerit at." value={this.props.descricaoTarefa} onChange={(e) => this.props.setDescricaoTarefa(e.target.value)} className="tarefadetalhada-duracao-5" /> 
        </div>
        <div className="tarefadetalhada-4">
            <div className="tarefadetalhada-4-0">
                <div className="tarefadetalhada-4-0-0">
                    <div className="tarefadetalhada-text_6">{"Tags:"}</div>
                </div>
            </div>
            <input type="text" placeholder="tag1, tag2" value={this.props.tags} onChange={(e) => this.props.setTags(e.target.value)} className="tarefadetalhada-text_input_5" /> 
        </div>
        <div className="tarefadetalhada-5">
            <div className="tarefadetalhada-5-0">
                <div className="tarefadetalhada-5-0-0">
                    <div className="tarefadetalhada-text_8">
                        {"Dependências:"}
                    </div>
                </div>
            </div>
            <input type="text" placeholder="13, 47, 58" value={this.props.dependencias} onChange={(e) => this.props.setDependencias(e.target.value)} className="tarefadetalhada-dependencias-9" /> 
        </div>
        <div className="tarefadetalhada-6">
            <div className="tarefadetalhada-6-0">
                <div className="tarefadetalhada-6-0-0">
                    <div className="tarefadetalhada-text_8-4">
                        {"Progresso:"}
                    </div>
                </div>
            </div>
            <input type="range" min="0" max="100" value={String(this.props.numeroProgresso)} onChange={(e) => this.props.setProgresso(e.target.value)} className="tarefadetalhada-slider-8" /> 
        </div>
        <div className="tarefadetalhada-7">
            <div className="tarefadetalhada-7-0">
                <div className="tarefadetalhada-7-0-0">
                    <div className="tarefadetalhada-text_8-1">
                        {"Descrição Progresso:"}
                    </div>
                </div>
            </div>
            <div className="tarefadetalhada-7-1">
                <div className="tarefadetalhada-7-1-0">
                    <input type="text" placeholder="Em espera" value={this.props.descricaoProgresso} onChange={(e) => this.props.setDescricao(e.target.value)} className="tarefadetalhada-dependencias-0" /> 
                </div>
            </div>
        </div>
        <div className="tarefadetalhada-8">
            <div className="tarefadetalhada-8-0">
                <div className="tarefadetalhada-8-0-0">
                    <div className="tarefadetalhada-mensagemerro-7">
                        { this.props.mensagemErro }
                    </div>
                </div>
            </div>
            <div className="tarefadetalhada-rectangle_2">
                <div className="tarefadetalhada-8-1-0">
                    <div onClick={this.props.handleClickSalvar} className="tarefadetalhada-botaosalvar-2">
                        <Componentebotao textoBotao={"Salvar"} color={this.props.corBotao} /> 
                    </div>
                </div>
            </div>
        </div>
        <div className="tarefadetalhada-9">
            <div className="tarefadetalhada-text_1">Feedbacks</div>
        </div>
        <div className="tarefadetalhada-10">
            <textarea placeholder="Escreva aqui seu feedback" value={this.props.feedbackInput} onChange={(e) => this.props.setNovoFeedback(e.target.value)} className="tarefadetalhada-feedbackinput-6" /> 
        </div>
        <div className="tarefadetalhada-11">
            <div className="tarefadetalhada-11-0">
                <div className="tarefadetalhada-11-0-0">
                    <div className="tarefadetalhada-text_15">{"Nota:"}</div>
                </div>
            </div>
            <div className="tarefadetalhada-11-1">
                <div className="tarefadetalhada-11-1-0">
                    <input type="text" placeholder="0-10" value={this.props.ratingInput} onChange={(e) => this.props.setNovoRating(e.target.value)} className="tarefadetalhada-ratinginput-4" /> 
                </div>
            </div>
            <div className="tarefadetalhada-rectangle_20">
                <div className="tarefadetalhada-11-2-0">
                    <div onClick={this.props.handleClickEnviar} className="tarefadetalhada-botaoenviar-3">
                        <Componentebotao textoBotao={"Enviar"} color={"rgb(17, 39, 73)"} /> 
                    </div>
                </div>
            </div>
        </div>
        <div className="tarefadetalhada-12">
            <div className="tarefadetalhada-12-0">
                { this.props.listaFeedbacks.map((elem, i) => {
                    return <div key={i} className="tarefadetalhada-rectangle_1">
                        <div className="tarefadetalhada-12-0-0-0-0">
                            <div className="tarefadetalhada-feedback_instance-9">
                                <Feedback autor={elem.autor} textoFeedback={elem.comentario} ratingFeedback={elem.nota} /> 
                            </div>
                        </div>
                    </div>;
                }) }
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
