// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Pasta from './pasta';
import Componentebotao from './componentebotao';
import Documento from './documento';
import './telaarquivo.css';


function render() {
    return <div className="telaarquivo-telaarquivo-0">
        <div className="telaarquivo-0">
            <div className="telaarquivo-arquivos-5">Arquivos</div>
        </div>
        <div className="telaarquivo-1">
            <div className="telaarquivo-pasta_instance-9">
                <Pasta /> 
            </div>
            <div className="telaarquivo-1-1">
                <div className="telaarquivo-1-1-0">
                    <div className="telaarquivo-componentebotao_instance_2">
                        <Componentebotao textoBotao={"Adicionar Arquivo"} /> 
                    </div>
                </div>
            </div>
        </div>
        <div className="telaarquivo-2">
            <div className="telaarquivo-text_5">
                ______________________________________________________________________________
            </div>
        </div>
        <div className="telaarquivo-3">
            <div className="telaarquivo-text_1">Recentes</div>
        </div>
        <div className="telaarquivo-4">
            <div className="telaarquivo-documento_instance-8">
                <Documento /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
