// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Menu from './menu';
import Barratarefas from './barratarefas';
import Centroequipes from './centroequipes';
import Barraagenda from './barraagenda';
import './telaequipes.css';


function render() {
    return <div className="telaequipes-telaequipes-0">
        <div className="telaequipes-0">
            <div className="telaequipes-menu_instance_2">
                <Menu nomeUsuario={this.props.nomeUsuario} /> 
            </div>
        </div>
        <div className="telaequipes-1">
            <div className="telaequipes-barratarefas_instance_2">
                <Barratarefas /> 
            </div>
            <div className="telaequipes-centroequipes_instance-2">
                <Centroequipes listaEquipes1={(this.props.listaEquipes1)} listaEquipes2={(this.props.listaEquipes2)} listaEquipes3={(this.props.listaEquipes3)} /> 
            </div>
            <div className="telaequipes-barraagenda_instance_2">
                <Barraagenda /> 
            </div>
        </div>
        <div className="telaequipes-2" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
