// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Menu from './menu';
import Barratarefas from './barratarefas';
import Barraagenda from './barraagenda';
import './telaequipes.css';


function render() {
    return <div className="telaequipes-telaequipes-0">
        <div className="telaequipes-0">
            <div className="telaequipes-menu_instance_2">
                <Menu /> 
            </div>
        </div>
        <div className="telaequipes-1">
            <div className="telaequipes-barratarefas_instance_2">
                <Barratarefas /> 
            </div>
            <div className="telaequipes-barraagenda_instance_2">
                <Barraagenda /> 
            </div>
        </div>
        <div className="telaequipes-2" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
