// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Menu from './menu';
import Barratarefas from './barratarefas';
import Centordetalheequipe from './centordetalheequipe';
import Barraagenda from './barraagenda';
import './teladetalheequipe.css';


function render() {
    return <div className="teladetalheequipe-teladetalheequipe-2">
        <div className="teladetalheequipe-0">
            <div className="teladetalheequipe-menu_instance_3">
                <Menu nomeUsuario={""} /> 
            </div>
        </div>
        <div className="teladetalheequipe-1">
            <div className="teladetalheequipe-barratarefas_instance_2">
                <Barratarefas /> 
            </div>
            <div className="teladetalheequipe-centordetalheequipe_instance-1">
                <Centordetalheequipe nomeEquipe={"Equipe qualquer"} membros={"arthur, paulo, pedro"} /> 
            </div>
            <div className="teladetalheequipe-barraagenda_instance_2">
                <Barraagenda /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
