// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Menu from './menu';
import Barratarefas from './barratarefas';
import Telaarquivo from './telaarquivo';
import Barraagenda from './barraagenda';
import './teladiretorio.css';


function render() {
    return <div className="teladiretorio-teladiretorio-9">
        <div className="teladiretorio-0">
            <div className="teladiretorio-menu_instance_1">
                <Menu nomeUsuario={this.props.nomeUsuario} /> 
            </div>
        </div>
        <div className="teladiretorio-1">
            <div className="teladiretorio-barratarefas_instance_2">
                <Barratarefas listaTarefas={this.props.listaMinhasTarefas} /> 
            </div>
            <div className="teladiretorio-telaarquivo_instance-6">
                <Telaarquivo dados={this.props.dados} /> 
            </div>
            <div className="teladiretorio-barraagenda_instance_2">
                <Barraagenda /> 
            </div>
        </div>
        <div className="teladiretorio-2" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
