// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Menu from './menu';
import Barratarefas from './barratarefas';
import Barraagenda from './barraagenda';
import './telaprincipal.css';


function render() {
    return <div className="telaprincipal-telaprincipal-6">
        <div className="telaprincipal-0">
            <div className="telaprincipal-menu_instance-1">
                <Menu nomeUsuario={this.props.nomeUsuario} /> 
            </div>
        </div>
        <div className="telaprincipal-1">
            <div className="telaprincipal-barratarefas_instance-2">
                <Barratarefas listaTarefas={[]} /> 
            </div>
            <div className="telaprincipal-barraagenda_instance-4">
                <Barraagenda /> 
            </div>
        </div>
        <div className="telaprincipal-2" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
