// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Menu from './menu';
import Barratarefas from './barratarefas';
import Centroadicionarequipe from './centroadicionarequipe';
import Barraagenda from './barraagenda';
import './telacriarequipe.css';


function render() {
    return <div className="telacriarequipe-telacriarequipe-9">
        <div className="telacriarequipe-0">
            <div className="telacriarequipe-menu_instance_2">
                <Menu nomeUsuario={""} /> 
            </div>
        </div>
        <div className="telacriarequipe-1">
            <div className="telacriarequipe-barratarefas_instance_2">
                <Barratarefas /> 
            </div>
            <div className="telacriarequipe-centroadicionarequipe_instance-1">
                <Centroadicionarequipe /> 
            </div>
            <div className="telacriarequipe-barraagenda_instance_2">
                <Barraagenda /> 
            </div>
        </div>
        <div className="telacriarequipe-2" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
