// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Menu from './menu';
import Barratarefas from './barratarefas';
import Projetos from './projetos';
import Barraagenda from './barraagenda';
import './telaprojetos.css';


function render() {
    return <div className="telaprojetos-telaprojetos-5">
        <div className="telaprojetos-0">
            <div className="telaprojetos-menu_instance_4">
                <Menu nomeUsuario={this.props.nomeUsuario} /> 
            </div>
        </div>
        <div className="telaprojetos-1">
            <div className="telaprojetos-barratarefas_instance_2">
                <Barratarefas /> 
            </div>
            <div className="telaprojetos-projetos_instance-9">
                <Projetos listaProjetos1={(this.props.listaProjetos1)} listaProjetos2={(this.props.listaProjetos2)} listaProjetos3={(this.props.listaProjetos3)} listaProjetos4={(this.props.listaProjetos4)} /> 
            </div>
            <div className="telaprojetos-barraagenda_instance_2">
                <Barraagenda /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
