// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import './tela_login.css';


function render() {
    return <div className="tela_login-tela_login-9">
        <div className="tela_login-0">
            <div className="tela_login-rectangle-6">
                <div className="tela_login-0-0-0">
                    <div className="tela_login-rectangle_5">
                        <div className="tela_login-0-0-0-0-0">
                            <div className="tela_login-0-0-0-0-0-0">
                                <div className="tela_login-0-0-0-0-0-0-0">
                                    <div className="tela_login-text-3">{"Usuário:"}</div>
                                </div>
                            </div>
                            <input type="text" placeholder="Digite usuário" className="tela_login-text_input-8" /> 
                        </div>
                    </div>
                </div>
                <div className="tela_login-0-0-1">
                    <div className="tela_login-rectangle_6">
                        <div className="tela_login-0-0-1-0-0">
                            <div className="tela_login-0-0-1-0-0-0">
                                <div className="tela_login-0-0-1-0-0-0-0">
                                    <div className="tela_login-text-9">{"Senha:"}</div>
                                </div>
                            </div>
                            <input type="text" placeholder="Placeholder" className="tela_login-text_input-0" /> 
                        </div>
                    </div>
                </div>
                <div className="tela_login-0-0-2">
                    <div className="tela_login-rectangle_3">
                        <div className="tela_login-0-0-2-0-0">
                            <div className="tela_login-text-36">Login</div>
                        </div>
                    </div>
                    <div className="tela_login-rectangle_4">
                        <div className="tela_login-0-0-2-1-0">
                            <div className="tela_login-rectangle_2">
                                <div className="tela_login-0-0-2-1-0-0-0">
                                    <div className="tela_login-text-4">Cancelar</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
