// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Menu from './menu';
import Barratarefas from './barratarefas';
import Adicionarprojeto from './adicionarprojeto';
import Barraagenda from './barraagenda';
import './telaadicionarprojeto.css';


function render() {
    return <div className="telaadicionarprojeto-telaadicionarprojeto-8">
        <div className="telaadicionarprojeto-0">
            <div className="telaadicionarprojeto-menu_instance_5">
                <Menu nomeUsuario={""} /> 
            </div>
        </div>
        <div className="telaadicionarprojeto-1">
            <div className="telaadicionarprojeto-barratarefas_instance_2">
                <Barratarefas /> 
            </div>
            <div className="telaadicionarprojeto-adicionarprojeto_instance-6">
                <Adicionarprojeto nomeProjeto={""} descricao={""} idEquipes={""} prazo={""} /> 
            </div>
            <div className="telaadicionarprojeto-barraagenda_instance_2">
                <Barraagenda /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
