// Generated by https://pagedraw.io/pages/10782
import React from 'react';
import Componentebotao from './componentebotao';
import './uploadarquivo.css';


function render() {
    return <div className="uploadarquivo-uploadarquivo-7">
        <div className="uploadarquivo-0">
            <div className="uploadarquivo-text_5">Upload Arquivo</div>
        </div>
        <div className="uploadarquivo-1">
            <div className="uploadarquivo-1-0">
                <div className="uploadarquivo-1-0-0">
                    <div className="uploadarquivo-text_9">{"Nome: "}</div>
                </div>
            </div>
            <input type="text" placeholder="Nome do arquivo" value={this.props.nome} className="uploadarquivo-text_input_2" /> 
        </div>
        <div className="uploadarquivo-2">
            <div className="uploadarquivo-file_input-3">
                <input type="file" /> 
            </div>
        </div>
        <div className="uploadarquivo-3">
            <div className="uploadarquivo-botaoupload-3">
                <Componentebotao textoBotao={"Upload"} /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
